### PR TITLE
Work with Python 3.8

### PR DESCRIPTION
**Pull request by hxdtest**
The OLMo doesn't work with Python 3.8. This is because cache is not available before Python 3.9 in functools and MutableMapping from  collections.abc doesn't work with  Python 3.8 as described [issue 446](https://github.com/allenai/OLMo/issues/446)

### CODE REVIEW

**Comment by natolambert** [comment]
Hey @hxdtest, this is a good start. Looks like theres maybe a github action issue with 3.8, which I can look at later, and linting is needed for the style check.

**Comment by hxdtest** [comment]
> Hey @hxdtest, this is a good start. Looks like theres maybe a github action issue with 3.8, which I can look at later, and linting is needed for the style check.

Thanks, I will fix the linting problem.

**Comment by natolambert** [comment]
Yeah this looks good, I'm checking with @epwalsh who just made a [commit](https://github.com/allenai/OLMo/commit/d9c09937e4ad3daef97d1cfdaf2bd948d9316296) temporarily requiring 3.9

**Review by epwalsh — APPROVED** [review]
LGTM, thanks @hxdtest!

**Pull request merged**
