### PR TITLE
add capability to output intermediate hidden states

### PR DESCRIPTION
**Pull request by sarahwie**
Add a functionality that HF model forward calls have. 
A very similar update can be done to add the `output_attentions` functionality, though I haven't written it yet.

Note that HF code "appends" hidden states to a tuple object, but I'm using a list as I think it's better practice. Hence the type casting in the function output to return a tuple, in order to match expected output in HF's convention.

### CODE REVIEW

**Comment by natolambert** [comment]
Have you tested this @sarahwie ? Looks close to what I would expect but I don't use the OLMo repo much :)

**Comment by AkshitaB** [comment]
Hi @sarahwie this is great! Do you mind also adding the use of the two flags to the HF wrapper here: https://github.com/allenai/OLMo/blob/main/hf_olmo/modeling_olmo.py#L48

**Review by AkshitaB — APPROVED** [review]

**Comment by sarahwie** [comment]
I've tested this locally but haven't re-built the pip package, let me try that to make sure it still works as expected @natolambert

**Comment by sarahwie** [comment]
Temporarily added code to throw an error if `output_attentions=True` (#449) since that functionality hasn't been coded yet as @natolambert pointed out.

 Tested this, and everything is worked as expected. Should I merge?

**Comment by natolambert** [comment]
@sarahwie probably, but I'm not a core contributor. If you changed a bunch more, you can ask @AkshitaB to review the recent changes.

**Pull request merged**
